GET http://localhost:5000/api/todos

###

POST http://localhost:5000/api/todo/new
Content-Type: application/json

{
    "title":"Ajay Ranabhat"
}

###

DELETE http://localhost:5000/api/todo/delete/63385320f5a9b7226eb3a864

###

GET http://localhost:5000/api/todo/toggleStatus/633853ece2e15af635c73e44